import {
    JWTToken,
    showfindAllUser,
    SoftwareFindAll,
    AreaFindAll,
    findAllSoftware,
    showHealthy,
    findAllElectricity,
    findAllShow,

    electricity,
    addEditelectricity,
    electricityDelete,

    softwareAll,
    softwarepage,
    softwareAdd,
    softwareDelete,

    districtpage,
    districtsave,
    districtfindAll,
    regionDelete,

    userhealth,
    addEditHealth,
    userhealthDelete,

    placepage,addEditPlace,
    placeDelete,
    ydtywebuseradmin,
    useradminregister,
    Delydtywebuseradmin,
    placepage, addEditPlace,
    placeDelete,

    areapage,
    areaAdd,
    areaDelete,
    areaAll,

    deploydistrictfindAll,
    deploydistrictAdd,
    deploydistrictDelete,

    bearuserpage,
} from './admin'

export default {
    JWTToken,
    showfindAllUser,
    SoftwareFindAll,
    AreaFindAll,
    findAllSoftware,
    showHealthy,
    findAllElectricity,
    findAllShow,

    electricity,
    addEditelectricity,
    electricityDelete,
    softwareAll,
    softwarepage,
    softwareAdd,
    softwareDelete,
    districtpage,
    districtsave,
    districtfindAll,
    regionDelete,
    userhealth,
    addEditHealth,
    userhealthDelete,
    placepage,
    addEditPlace,
    placeDelete,
    ydtywebuseradmin,
    useradminregister,
    Delydtywebuseradmin,
    areapage,
    areaAdd,
    areaDelete,
    areaAll,
    deploydistrictfindAll,
    deploydistrictAdd,
    deploydistrictDelete,
    bearuserpage,
}